baseurl: '/semanticsofcancer.com/'
permalink: 'pretty'
title: 'The Semantics of Cancer'

logo:
  mobile: "images/cell-icon.png"
  mobile_height: "32px"
  mobile_width: "38px"
  desktop: "images/logo-side.png"
  desktop_height: "87px"
  desktop_width: "405px"

home: 
  limit_services: 3

collections:
  services:
    output: true
    sort_by: weight
  team:
    output: true

defaults:
  - scope:
      path: ""
      type: "services"
    values:
      layout: "service"
  - scope:
      path: ""
      type: "team"
    values:
      layout: "team"

sass:
  style: compressed # possible values: nested expanded compact compressed

plugins:
  - jekyll-environment-variables

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE.md
  - LICENSE
  - README.md
